services:
  mongodb:
    image: mongo:latest
    container_name: supermarket-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      target: development
    container_name: supermarket-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://root:example@mongodb:27017/supermarket-query
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start:dev

volumes:
  mongodb_data:
