#!/usr/bin/env sh

# Run the OpenAPI types generation script
sh "$(dirname -- "$0")/generate-openapi.sh"

# Run the Prisma client generation script
sh "$(dirname -- "$0")/generate-prisma.sh" 

sh "$(dirname -- "$0")/generate-consumer-backend-client.sh"
